Update Gaia API documents for #6415b8b44068596404c10365394544e94edd5ce5     Revert "Merge pull request #14529 from jaoo/933203"
This reverts commit 4dd40d64f137c48104d5f39e48c2ccb0ce9ab78c, reversing
changes made to 0985280ffc917353eb34ff7b0dcc1c152856450c.

This is breaking unit tests:
[system] system/LockScreenConnInfoManager > Single sim devices "before each" hook:
TypeError: MockNavigatorMozIccManager.addIcc is not a function